### ISSUE TITLE
[Question] performance with forwardproxy

### ISSUE THREAD

**Issue by npwc** [bjin/hprox#2]
A fantastic tool, has anyone compared its performance with [forwardproxy](https://github.com/caddyserver/forwardproxy)?

**Comment by bjin** [comment]
The performance of a proxy server involves multiple factors and is usually difficult to compare in fair and yet realistic environment. Also, the bottle neck of performance is mostly limited by ISP and tier 1 global network packet losses. For QUIC/HTTP3, UDP QoS performed by local ISP is yet another significant factor.

However, regarding the HTTP server alone, `hprox` is built with [warp](https://hackage.haskell.org/package/warp) which is a well known high performance HTTP Server implementation, you can find technical details from [this book](https://aosabook.org/en/posa/warp.html).
