### ISSUE TITLE
Can hprox Loging authentication information?

### ISSUE THREAD

**Issue by mshigemoto** [bjin/hprox#4]
I tried your hprox. Very nice project. Usage is simple. I feel it reacts quickly.

I have a question.
Can  hprox write the username (authentication information) to the log? 

I use hprox with --loglevel with each all loglevel option. but user information did not appear.

Caddy can log the authenticate information by using  Base64, and Shadowsocks can write the authenticate information in plaintext to the log.

Do you have similar functionality? If not, are there any plans to implement it in the future?

**Comment by bjin** [comment]
> Can hprox write the username (authentication information) to the log?

Currently `hprox` will only show name of authentication files in log, but not detailed user information, whether base64-encoded or in plaintext. What's the purpose of reading such informations from logging?

> Caddy can log the authenticate information by using Base64, and Shadowsocks can write the authenticate information in plaintext to the log.

`hprox` support HTTP basic authentications with option `-a/--auth userpass.txt`, it's a text file with multiple lines (for multiple user support), each line contains a `user:pass` pairs in plaintext. In addition, all failed authentication will be logged with `WARN` log level, and that's all.

**Comment by mshigemoto** [comment]
Thanks for the quick reply. 

>What's the purpose of reading such informations from logging?

(1)
 I want to provide my server to multiple users. So I want to know which users used the server and when. 

(2)
In addition, if the user name is included in log like as ...

   `unauthorized request (username):, `

it can help to see which user has trouble with the wrong password.

I sincerely hope for this feature. Is this a difficult request?

**Comment by bjin** [comment]
You can now enable `--loglevel trace` to see all proxy authentication outcomes, something like
```
[TRACE] authorized request (credential: user:pass) from X.X.X.X
```

You can also find statically linked binary of git master at [circleci artifacts page](https://app.circleci.com/pipelines/github/bjin/hprox/125/workflows/5ff33f46-c84b-43c5-aae4-4828a5000515/jobs/138/artifacts), once the compilation is finished.

**Comment by mshigemoto** [comment]
Thank you so so much.
I really appreciate your work.
I will try the new version.

**Comment by mshigemoto** [comment]
I compiled from source code and tried it.
I was able to log in exactly the format I wanted.
Thanks so much!
