### ISSUE TITLE
The transparency to the GFW when used without the --naive option

### ISSUE THREAD

**Issue by mshigemoto** [bjin/hprox#5]
I like hprox very much.  thank you.

Question:
Even If using hprox **without** the` --naive `option, does It has probe resistance for GFW?
If so, which is better to use with the `--naive` option or not?

**Comment by bjin** [comment]
> Even If using hprox without the--naiveoption, does It has probe resistance for GFW?

No, payload padding is necessary for such purposes. Also you may want to add `--hide` option for probe resistance. With `--hide` option `hprox` will never send `proxy authentication required response`.

**Comment by mshigemoto** [comment]
I see, thank you!
And I will user the `--hide` option.
